### ISSUE TITLE
Bootstrap panics when running dist

### ISSUE THREAD

**Issue by aleasims** [NilFoundation/zkllvm-rslang#14]
Running `./x dist` with zkllvm config results into a panic:
```
Dist rust-1.68.0-dev-x86_64-unknown-linux-gnu
	finished in 222.474 seconds
thread 'main' panicked at 'cmd.output() failed with No such file or directory (os error 2)', dist.rs:988:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: <bootstrap::dist::PlainSourceTarball as bootstrap::builder::Step>::run
             at ./src/bootstrap/dist.rs:988:38
   3: bootstrap::builder::Builder::ensure
             at ./src/bootstrap/builder.rs:1966:23
   4: <bootstrap::dist::PlainSourceTarball as bootstrap::builder::Step>::make_run
             at ./src/bootstrap/dist.rs:928:9
   5: bootstrap::builder::StepDescription::maybe_run
             at ./src/bootstrap/builder.rs:297:13
   6: bootstrap::builder::StepDescription::run
             at ./src/bootstrap/builder.rs:334:21
   7: bootstrap::builder::Builder::run_step_descriptions
             at ./src/bootstrap/builder.rs:893:9
   8: bootstrap::builder::Builder::execute_cli
             at ./src/bootstrap/builder.rs:873:9
   9: bootstrap::Build::build
             at ./src/bootstrap/lib.rs:752:13
  10: bootstrap::main
             at ./src/bootstrap/bin/main.rs:50:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
```

**Comment by aleasims** [comment]
File which was not found is `cargo` itself. The problem happens because in the config file `src/bootstrap/defaults/config.zkllvm.toml` path to `cargo` was relative:

```
cargo = "target/release/cargo"
```

During the dist phase bootstrap changed working directory thus `cargo` was not found and that caused a panic.

Changing path to `cargo` to absolute fixes the problem.
