### ISSUE TITLE
Panic on re-compilation of changed code

### ISSUE THREAD

**Issue by aleasims** [NilFoundation/zkllvm-rslang#15]
Reproduce:

1. Compile code
2. Change something in it
3. Compile again without clearing `target` directory

This leads to codegen panic:

```
thread 'copy 4xy1b6llaoztkio6' panicked at 'assertion failed: module_config.emit_obj != EmitObj::None', /root/proj/zkllvm/libs/rslang/compiler/rustc_codegen_ssa/src/back/write.rs:864:5
stack backtrace:
   0:     0x7f837431f851 - std::backtrace_rs::backtrace::libunwind::trace::h448ca9cc1e1e6c18
                               at /root/proj/zkllvm/libs/rslang/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f837431f851 - std::backtrace_rs::backtrace::trace_unsynchronized::h98f1e75adc87f715
                               at /root/proj/zkllvm/libs/rslang/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f837431f851 - std::sys_common::backtrace::_print_fmt::hc1a2ea13c6663fc9
                               at /root/proj/zkllvm/libs/rslang/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f837431f851 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha351bf8a6c32deea
                               at /root/proj/zkllvm/libs/rslang/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f83743920b8 - core::fmt::write::h55531ca8defb37cb
                               at /root/proj/zkllvm/libs/rslang/library/core/src/fmt/mod.rs:1213:17
   5:     0x7f83742e5621 - std::io::Write::write_fmt::h16951de5f4dcce82
                               at /root/proj/zkllvm/libs/rslang/library/std/src/io/mod.rs:1682:15
   6:     0x7f837431f645 - std::sys_common::backtrace::_print::ha8093f2c1f2e1e0b
                               at /root/proj/zkllvm/libs/rslang/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f837431f645 - std::sys_common::backtrace::print::h90aa136d18824797
                               at /root/proj/zkllvm/libs/rslang/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f83742e7484 - std::panicking::default_hook::{{closure}}::h64abe71e4f46a778
   9:     0x7f83742e70ef - std::panicking::default_hook::h9b76477430006fc7
                               at /root/proj/zkllvm/libs/rslang/library/std/src/panicking.rs:286:9
  10:     0x7f83754164a2 - <alloc[1af7e9a647a3acbd]::boxed::Box<dyn for<'a, 'b> core[61b3469cae6f780b]::ops::function::Fn<(&'a core[61b3469cae6f780b]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[61b3469cae6f780b]::marker::Sync + core[61b3469cae6f780b]::marker::Send> as core[61b3469cae6f780b]::ops::function::Fn<(&core[61b3469cae6f780b]::panic::panic_info::PanicInfo,)>>::call
                               at /root/proj/zkllvm/libs/rslang/library/alloc/src/boxed.rs:2002:9
  11:     0x7f83754164a2 - rustc_driver[de6373d308547c93]::DEFAULT_HOOK::{closure#0}::{closure#0}
                               at /root/proj/zkllvm/libs/rslang/compiler/rustc_driver/src/lib.rs:1160:17
  12:     0x7f83742e7da8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd3bd37c69d6e36ad
                               at /root/proj/zkllvm/libs/rslang/library/alloc/src/boxed.rs:2002:9
  13:     0x7f83742e7da8 - std::panicking::rust_panic_with_hook::h287f97185cb9b11c
                               at /root/proj/zkllvm/libs/rslang/library/std/src/panicking.rs:692:13
  14:     0x7f8374320ca2 - std::panicking::begin_panic_handler::{{closure}}::hfc4e2546eba11b77
                               at /root/proj/zkllvm/libs/rslang/library/std/src/panicking.rs:577:13
  15:     0x7f837431f99c - std::sys_common::backtrace::__rust_end_short_backtrace::h33c01666c42ba6bf
                               at /root/proj/zkllvm/libs/rslang/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x7f83742e78c2 - rust_begin_unwind
                               at /root/proj/zkllvm/libs/rslang/library/std/src/panicking.rs:575:5
  17:     0x7f83742a67b3 - core::panicking::panic_fmt::h2bc6425dbedc4beb
                               at /root/proj/zkllvm/libs/rslang/library/core/src/panicking.rs:64:14
  18:     0x7f83742a684d - core::panicking::panic::ha6f66b7567be4a8e
                               at /root/proj/zkllvm/libs/rslang/library/core/src/panicking.rs:114:5
  19:     0x7f837576b767 - rustc_codegen_ssa[e3d6c87947e862f1]::back::write::execute_copy_from_cache_work_item::<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>
  20:     0x7f837576b767 - rustc_codegen_ssa[e3d6c87947e862f1]::back::write::execute_work_item::<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>
                               at /root/proj/zkllvm/libs/rslang/compiler/rustc_codegen_ssa/src/back/write.rs:754:16
  21:     0x7f83758864f9 - rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work::<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}
                               at /root/proj/zkllvm/libs/rslang/compiler/rustc_codegen_ssa/src/back/write.rs:1694:18
  22:     0x7f83758864f9 - <rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread::<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}
                               at /root/proj/zkllvm/libs/rslang/compiler/rustc_codegen_llvm/src/lib.rs:163:13
  23:     0x7f83758864f9 - std[1fa0a71b0a20452a]::sys_common::backtrace::__rust_begin_short_backtrace::<<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>
                               at /root/proj/zkllvm/libs/rslang/library/std/src/sys_common/backtrace.rs:121:18
  24:     0x7f837588de9c - <std[1fa0a71b0a20452a]::thread::Builder>::spawn_unchecked_::<<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>::{closure#1}::{closure#0}
                               at /root/proj/zkllvm/libs/rslang/library/std/src/thread/mod.rs:558:17
  25:     0x7f837588de9c - <core[61b3469cae6f780b]::panic::unwind_safe::AssertUnwindSafe<<std[1fa0a71b0a20452a]::thread::Builder>::spawn_unchecked_<<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>::{closure#1}::{closure#0}> as core[61b3469cae6f780b]::ops::function::FnOnce<()>>::call_once
                               at /root/proj/zkllvm/libs/rslang/library/core/src/panic/unwind_safe.rs:271:9
  26:     0x7f837588de9c - std[1fa0a71b0a20452a]::panicking::try::do_call::<core[61b3469cae6f780b]::panic::unwind_safe::AssertUnwindSafe<<std[1fa0a71b0a20452a]::thread::Builder>::spawn_unchecked_<<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /root/proj/zkllvm/libs/rslang/library/std/src/panicking.rs:483:40
  27:     0x7f837588de9c - std[1fa0a71b0a20452a]::panicking::try::<(), core[61b3469cae6f780b]::panic::unwind_safe::AssertUnwindSafe<<std[1fa0a71b0a20452a]::thread::Builder>::spawn_unchecked_<<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>::{closure#1}::{closure#0}>>
                               at /root/proj/zkllvm/libs/rslang/library/std/src/panicking.rs:447:19
  28:     0x7f837588de9c - std[1fa0a71b0a20452a]::panic::catch_unwind::<core[61b3469cae6f780b]::panic::unwind_safe::AssertUnwindSafe<<std[1fa0a71b0a20452a]::thread::Builder>::spawn_unchecked_<<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>::{closure#1}::{closure#0}>, ()>
                               at /root/proj/zkllvm/libs/rslang/library/std/src/panic.rs:140:14
  29:     0x7f837588de9c - <std[1fa0a71b0a20452a]::thread::Builder>::spawn_unchecked_::<<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>::{closure#1}
                               at /root/proj/zkllvm/libs/rslang/library/std/src/thread/mod.rs:557:30
  30:     0x7f837588de9c - <<std[1fa0a71b0a20452a]::thread::Builder>::spawn_unchecked_<<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend as rustc_codegen_ssa[e3d6c87947e862f1]::traits::backend::ExtraBackendMethods>::spawn_named_thread<rustc_codegen_ssa[e3d6c87947e862f1]::back::write::spawn_work<rustc_codegen_llvm[92d53c3cd8b40753]::LlvmCodegenBackend>::{closure#0}, ()>::{closure#0}, ()>::{closure#1} as core[61b3469cae6f780b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /root/proj/zkllvm/libs/rslang/library/core/src/ops/function.rs:250:5
  31:     0x7f83742d5a68 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h34b766fa54b16994
                               at /root/proj/zkllvm/libs/rslang/library/alloc/src/boxed.rs:1988:9
  32:     0x7f83742d5a68 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he5188cb66fb76806
                               at /root/proj/zkllvm/libs/rslang/library/alloc/src/boxed.rs:1988:9
  33:     0x7f83742c7585 - std::sys::unix::thread::Thread::new::thread_start::h84be2d2ccc12d4a3
                               at /root/proj/zkllvm/libs/rslang/library/std/src/sys/unix/thread.rs:108:17
  34:     0x7f837408eb43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  35:     0x7f8374120a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  36:                0x0 - <unknown>

error: internal compiler error: unexpected panic
```

**Comment by aleasims** [comment]
Can't reproduce, so closing for now.
